### PR TITLE
Improved Atari 7800 palette for NTSC and PAL

### PR DESCRIPTION
**Pull request by trebor68**
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please remember to link related Issues! If a bug hasn't been reported, you may submit a fix without creating an Issue."

(describe changeset here)

[//]: # "Apart from the mandatory license signature, these tasks are optional, but doing them could save reviewers some time and get the PR merged sooner."
Check if completed:
- [x] I have run any relevant test suites
- [x] I, the committer, have read the [licensing terms for contributors](https://github.com/TASEmulators/BizHawk/blob/master/contributing.md#copyrights-and-licensing) (last updated 2022-07-15) and am compliant

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Can you post some comparison pics?

**Comment by trebor68** [comment]
Current Palette results are on the left, update submission results are on the right.
BizHawk78_BeforeNAfterpng

**Comment by YoshiRulz** [comment]
[8e9bc1f31ef2e608ede7af20fbe38d0033f46e55.patch.txt](https://github.com/TASEmulators/BizHawk/files/15140810/8e9bc1f31ef2e608ede7af20fbe38d0033f46e55.patch.txt)

**Comment by trebor68** [comment]
Respecting that patch text file, from this reference: http://atariage.com/forums/topic/95498-7800-color-palette-in-mess/?p=1174461

We have come a considerable way with Atari 7800 palette understanding since 2006.  

This post would be the latest: https://forums.atariage.com/topic/322259-trebors-pro-palettes-and-colors-guide-with-conversions/?do=findComment&comment=5331666

The entire thread is worth the read, IMHO.

Majority of PAL units, even after warm-up demonstrate a COOL palette.  
Majority of NTSC units after warm-up demonstrate a HOT palette.  

Ideally, displays would be calibrated for brightness and contrast per the CPS 7800 Diagnostic Cart.

Colors should reflect how they would appear under a CRT as that was the target display device of developers and how label interpretation for the hues was derived back in the day. 

[NTSC_CRT_CALIBRATED_HOT.txt](https://github.com/TASEmulators/BizHawk/files/15141896/NTSC_CRT_CALIBRATED_HOT.txt)
[PAL_CRT_CALIBRATED_COOL.txt](https://github.com/TASEmulators/BizHawk/files/15141898/PAL_CRT_CALIBRATED_COOL.txt)

Hexadecimal data is listed out in the above attached files.

**Pull request closed without merging**
