### PR TITLE
Change OnMovieEnd default to 'Pause' instead of 'Finish'

### LINKED ISSUE #4007: Change default for `OnMovieEnd` to "Pause" instead of "Finished"
I think the default `On Movie End` state should be `Pause`, not `Switch to Finished`.

I believe the basic argument in favor is relatively simple and compelling: if a movie is paused, you merely have to unpause and it will be in the "Finished" state. **In contrast:** if a movie plays into Finished state, it will continue playing indefinitely and you probably have to replay the entire movie from the start to reach the exact end, which is time-consuming for long movies.

## Extra notes
1. As a side-note, I'm actually not sure what Finished's use-case is in modern times. Rarely if ever is there utility in playing a movie indefinitely past the movie end. You can barely do anything in Finished mode as far as I'm aware: you cannot modify or continue the current movie so anything you do afterwards won't be saved. It does serve to let you know you were previously playing a movie, and it does accept inputs, but those inputs are not going to be saved if you're trying to do serious testing.
2. I realize this is a long-standing default (introduced in b53cc908b8e2543e8a8ca4869121c96e73e27ed9 on Jul 14, 2014 for 1.7.1), maybe even inherited from FCEUX, but I do still think it should be changed. Finished mode was the *only* movie end option prior to the other options being introduced, so it seems to have been chosen as the default because of that.
3. (Tangentially, at time of writing, I actually think there might be a change to the emulator behavior where it prevents savestate saves on the last frame in 2.9.2 dev, which I don't think was the behavior prior and disrupts traditional movie recording (where a workflow for continuing a movie can be playing the whole movie and saving a savestate at the end, then loading the savestate). I vaguely recall seeing that commit. I'll try and move this to another issue when I have time to confirm.)

Semi-related: #3989

### PR DESCRIPTION
**Pull request by RetroEdit**
Fixes #4007

Check if completed:
- [x] I have run any relevant test suites
- [x] I, the committer, have read the [licensing terms for contributors](https://github.com/TASEmulators/BizHawk/blob/master/contributing.md#copyrights-and-licensing) (last updated 2024-06-22) and am compliant

### CODE REVIEW

**Review by YoshiRulz — APPROVED** [review]

**Comment by vadosnaprimer** [comment]
What happens after you unpause? Does the movie unload?

**Comment by YoshiRulz** [comment]
It's using the existing setting. This only changes which is the default.

**Comment by vadosnaprimer** [comment]
Is my question impossible to answer?

**Comment by RetroEdit** [comment]
@feos It changes to Finished. Thus, you lose no functionality with this new functionality, and gain substantial convenience.

**Review by vadosnaprimer — APPROVED** [review]

**Pull request merged**
