### PR TITLE
Set some Saturn memory areas to swapped

### PR DESCRIPTION
**Pull request by sozud**
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please remember to link related Issues! If a bug hasn't been reported, you may submit a fix without creating an Issue."

Some of the Saturn memory areas seem to be in the wrong byte order. For example:

image

vs. after this change:

image

High Work Ram is pretty obvious but I'm not as sure about the other areas.

Is there a test suite to run for this?

[//]: # "Apart from the mandatory license signature, these tasks are optional, but doing them could save reviewers some time and get the PR merged sooner."
Check if completed:
- [ ] I have run any relevant test suites
- [x] I, the committer, have read the [licensing terms for contributors](https://github.com/TASEmulators/BizHawk/blob/master/contributing.md#copyrights-and-licensing) (last updated 2022-07-15) and am compliant

### CODE REVIEW

**Comment by CasualPokePlayer** [comment]
Checking meda's code, it would seem that all the domains, except Backup Ram and Backup Cart, would be byteswapped

**Comment by sozud** [comment]
Ok to make sure I understand, is this what you mean?

```
Not swapped:
Backup Ram
Backup Cart

Swapped:
Sound Ram
Boot Rom
Work Ram Low
Work Ram High
VDP1 Ram
VDP1 Framebuffer
VDP2 Ram
VDP2 Cram
CS1 Cart
Ram Cart
Rom Cart
```

**Comment by CasualPokePlayer** [comment]
Correct

**Comment by CasualPokePlayer** [comment]
2ce3bbffa557d2acec7c38fe63cc86a4f5de4385 fixes this issue

**Pull request closed without merging**
