### PR TITLE
Implement memory callbacks for the new bsnes core

### PR DESCRIPTION
**Pull request by Morilli**
Basically, everything "works" but the moment a callback gets executed bizhawk crashes. I can not pinpoint what is going on or what is crashing because apparently memory gets corrupted so badly the execution jumps into places it shouldn't be able to.

No idea what's going on or how to fix it, so I'm just putting this here for feedback because it would probably be nice to have this at some point.
Also it's likely libco.

If anyone wants to test, I'm using the `SMW-BizHawk.lua` script from https://github.com/brunovalads/smw-stuff (needs super mario world rom) with the `Lagmeter` option enabled (which executes get_registers on callback).

### CODE REVIEW

**Comment by nattthebear** [comment]
Haven't looked yet, but is the crash just #2585?

**Comment by Morilli** [comment]
>Haven't looked yet, but is the crash just #2585?

Hmm, you might be right about that. I guess whenever host code was calling core functions before it was never a reentrant call.

**Comment by Morilli** [comment]
Have rebased onto #3007; should be in a working state now.

**Comment by vadosnaprimer** [comment]
So this one is ready too?

**Comment by vadosnaprimer** [comment]
```
[19:49:56] <natt> The idea seems fine
[19:51:02] <natt> In particular, with modern waterbox it is 100% legal and allowed to have the following call sequence:  1) Emuhawk calls waterbox frameadvance. 2) Transition to guest  code and start frame advance.  3)  Guest code switches to a different libsnes cothread 4) Guest code calls back into host space.
[19:51:32] <natt> 3 and 4 don't need a thread transition between them.  The host does not require the guest to have any particular stack pointer value for #4 (just that it has to be a legal memory address in the guest)
[19:51:53] <natt> I spent a lot of effort making that work and this is the payout
[19:53:17] <natt> (With classic native code, using cothreads like that would cause 4) to have C# managed code running on something which is not understood by win32 as a thread, and creates a giant mess sometimes)
```

**Pull request merged**
