### PR TITLE
Refactor InputDisplayGenerator and LogEntryGenerator handling

### PR DESCRIPTION
**Pull request by Morilli**
This PR aims to simplify the `Bk2InputDisplayGenerator` and `Bk2LogEntryGenerator` handling, especially in regards to the many `IController` classes that exist, and improve caching.

Is this safe? It *should* be. Further simplifying the different controller types would help with the clarity here.

Basically, there is now one `InputDisplayGenerator` field on the `InputManager` class that always uses the `ActiveController`'s `ControllerDefinition` as basis. As far as I understand the code, that's all that's required but it was being handled much more complicated before.

Additionally I've added a `ILogEntryController : IController` interface that is now applied to `IMovieController` as well, and just contains one `Bk2LogEntryGenerator` cached as a field on the `ILogEntryController` to be used for log entry generation from that controller, without having to create a new one every time or caching it on a `Bk2Movie` (which was apparently problematic before: f6135abe652fddc5c28e4bc61a36d13a4c801cfd).

### CODE REVIEW

**Comment by kalimag** [comment]
I get NREs on `Session.MovieController` when trying to open TAStudio or record a movie straight after launching BizHawk. Doesn't happen if I play a movie first.

```
   at BizHawk.Client.EmuHawk.TAStudio.get_ControllerType() in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.EmuHawk\tools\TAStudio\TAStudio.ListView.cs:line 69
   at BizHawk.Client.EmuHawk.TAStudio.SetupBoolPatterns() in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.EmuHawk\tools\TAStudio\TAStudio.cs:line 436
   at BizHawk.Client.EmuHawk.TAStudio.Engage() in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.EmuHawk\tools\TAStudio\TAStudio.cs:line 221
   at BizHawk.Client.EmuHawk.TAStudio.Tastudio_Load(Object sender, EventArgs e) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.EmuHawk\tools\TAStudio\TAStudio.cs:line 161
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at BizHawk.Client.EmuHawk.FormBase.OnLoad(EventArgs e) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.EmuHawk\FormBase.cs:line 71
```

```
   at BizHawk.Client.Common.Bk2Movie.WriteInputLog(TextWriter writer) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\movie\bk2\Bk2Movie.InputLog.cs:line 18
   at BizHawk.Client.Common.ZipStateSaver.<>c__DisplayClass7_0.<PutLump>b__0(Stream s) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\savestates\ZipStateSaver.cs:line 56
   at BizHawk.Client.Common.FrameworkZipWriter.WriteItem(String name, Action`1 callback, Boolean zstdCompress) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\FrameworkZipWriter.cs:line 44
   at BizHawk.Client.Common.ZipStateSaver.PutLump(BinaryStateLump lump, Action`1 callback, Boolean zstdCompress) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\savestates\ZipStateSaver.cs:line 37
   at BizHawk.Client.Common.ZipStateSaver.PutLump(BinaryStateLump lump, Action`1 callback) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\savestates\ZipStateSaver.cs:line 53
   at BizHawk.Client.Common.Bk2Movie.AddBk2Lumps(ZipStateSaver bs) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\movie\bk2\Bk2Movie.IO.cs:line 90
   at BizHawk.Client.Common.Bk2Movie.AddLumps(ZipStateSaver bs, Boolean isBackup) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\movie\bk2\Bk2Movie.IO.cs:line 81
   at BizHawk.Client.Common.Bk2Movie.Write(String fn, Boolean isBackup) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\movie\bk2\Bk2Movie.IO.cs:line 44
   at BizHawk.Client.Common.Bk2Movie.Save() in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.Common\movie\bk2\Bk2Movie.IO.cs:line 15
   at BizHawk.Client.EmuHawk.RecordMovie.Ok_Click(Object sender, EventArgs e) in H:\Projekte\Visual Studio\BizHawk-upstream\src\BizHawk.Client.EmuHawk\movie\RecordMovie.cs:line 270
   ...
```

**Comment by tommai78101** [comment]
I get a `NullReferenceException` when attempting to load TAStudio. I need TAStudio to open before I can run my external tool.

```csharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.TAStudio.UpdateAutoFire(String button, Nullable`1 isOn)
   at BizHawk.Client.EmuHawk.TAStudio.UpdateAutoFire()
   at BizHawk.Client.EmuHawk.TAStudio.LoadFile(FileInfo file, Boolean startsFromSavestate, Int32 gotoFrame)
   at BizHawk.Client.EmuHawk.TAStudio.Engage()
   at BizHawk.Client.EmuHawk.TAStudio.Tastudio_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at BizHawk.Client.EmuHawk.FormBase.OnLoad(EventArgs e)
```

**Comment by Morilli** [comment]
> I get a `NullReferenceException` when attempting to load TAStudio.

When does this happen? Just opening TAStudio works fine for me, are there certain steps required?

**Comment by tommai78101** [comment]
> > I get a `NullReferenceException` when attempting to load TAStudio.
> 
> When does this happen? Just opening TAStudio works fine for me, are there certain steps required?

Yes, You need to have an external tool set to auto-load a game when EmuHawk starts, which means TAStudio will also need to be set to auto-load a TASPROJ file when EmuHawk launches as well.

Let me know if you need more information.

**Comment by Morilli** [comment]
I just get `BENIGN: Couldn't find type GeneticAlgorithmBot.GeneticAlgorithmBot` and it doesn't even autoload the external tool at all...

**Comment by tommai78101** [comment]
> I just get `BENIGN: Couldn't find type GeneticAlgorithmBot.GeneticAlgorithmBot` and it doesn't even autoload the external tool at all...

You're using the wrong build. That's an older version prior to the Bot settings file changes pre-v2.9 release. Here's the actual latest build.

[GeneticAlgorithmBot-v1.0.4-dev.zip](https://github.com/TASEmulators/BizHawk/files/12389971/GeneticAlgorithmBot-v1.0.4-dev.zip)

**Comment by adelikat** [comment]
I'm really excited to see this change

**Pull request closed without merging**
