### PR TITLE
Emu83

### PR DESCRIPTION
**Pull request by CasualPokePlayer**
Brand new TI83 emulator made by me in C. Much faster emulation, probably around the same accuracy, savestates actually work with the link port emulation, and can handle multiple files sent in at once via multidisk manager (can't send files through mid-emulation, sorry).

Don't know what to do with the existing TI83 emulator, it's mostly just not usable for TASing anyways due to link port not being stated and requiring manual input if multiple files want to be sent through (common for games which often have prerequisite files). Maybe someone will care enough to fix those issues, maybe not, idk

### CODE REVIEW

**Comment by nattthebear** [comment]
I'm surprised this works on Linux.  At one point our native library loading was so fubared that DllImport was essentially unusable for a crossplatform lib.  Glad to see we fixed that.

**Comment by alyosha-tas** [comment]
Cool! Should definitely remove the old core. But why the huge table for DAA?

**Comment by CasualPokePlayer** [comment]
> Cool! Should definitely remove the old core. But why the huge table for DAA?

Too lazy to figure out some decent code for DAA so I just generated a LUT.

**Comment by TiKevin83** [comment]
[DaleksSpeedcodeEmu83.zip](https://github.com/TASEmulators/BizHawk/files/7919847/DaleksSpeedcodeEmu83.zip)
I moved the inputs over from the daleks speedcode and everything seems to sync up great (had to add a column to the input for the SEND button). Runs way better than the old core, the old core couldn't play at full speed on current gen hardware if TASTudio was open.

**Comment by InfamousKnight** [comment]
How do you use this emulator? I found ti 83 games online but I could never figure out how to open them..

**Comment by CasualPokePlayer** [comment]
> How do you use this emulator? I found ti 83 games online but I could never figure out how to open them..

Provide the TI83 "Rom" in the firmware folder.
Then open up TI83 games with "Open ROM" (if multiple files are needed, pass it through the multidisk bundler).
Make sure you actually press the "ON" button.
To send a game through to the calculator, the "SEND" button must be pressed. This is a new button in this emulator as an indicator to send the next file over.
Press the "PRGM" button to enter the program list. This will have your games once you send them over.
Games might not run out of the box, they may need prerequisite programs like ION and MirageOS to run them. Make sure you read the game page for info on how to launch these games.

**Comment by InfamousKnight** [comment]
Wait, so place the game rom in the firmware folder? Or bios rom like any other core?

And where's this page you're talking about?

**Comment by CasualPokePlayer** [comment]
> Wait, so place the game rom in the firmware folder? Or bios rom like any other core?
The firmware is called the "Rom" and is just a simple OS from TI. The actual games are not cartridges obviously, but rather programs sent through the link port (essentially "link files") which go through the "Open ROM"/multidisk bundler interface

> And where's this page you're talking about?
The page where you download your game? They are all homebrew games coming from the same host website with pages for every entry.

**Comment by TiKevin83** [comment]
I'll make a demo video that shows how it works more in depth

**Comment by InfamousKnight** [comment]
> I'll make a demo video that shows how it works more in depth

Sounds good. I'm surprised by how much homebrew this core has.

**Comment by InfamousKnight** [comment]
> I'll make a demo video that shows how it works more in depth

Sounds good. I'm surprised by how much homebrew this core has.

**Comment by TiKevin83** [comment]
The TI-83 was a required tool for standardized tests in the US for ~20 years thus having tens to hundreds of millions of users

**Comment by TiKevin83** [comment]
As part of making the example video I ran into this file - the .83G file in this is detected as an Atari game?
[bmarines.zip](https://github.com/TASEmulators/BizHawk/files/7965099/bmarines.zip)

Also can we get the ability to load .83P and .83G files directly outside of a zip file?

**Comment by TiKevin83** [comment]
@InfamousKnight 
https://youtu.be/o_G9ADCMpow

**Review by TiKevin83 — APPROVED** [review]
approving and making a separate issue for the UI on button issue

**Pull request merged**
