### PR TITLE
Add auto save state on close

### PR DESCRIPTION
**Pull request by peteyus**
- Add configuration for auto-saving state on exit
- Update MainForm to auto save on close game if configured
- Fix config serialization test.

#1861

### CODE REVIEW

**Review by YoshiRulz — CHANGES_REQUESTED** [review]
The new setting(s) should be beside the autoload setting in `File` > `Load State`. That means the config properties are in the wrong class too.

This autosave uses a specific, configurable slot, but the autoload counterpart uses the currently selected slot:
https://github.com/TASEmulators/BizHawk/blob/8ea09eebf591a88b679d01f70784b84fd8fcbe5b/src/BizHawk.Client.EmuHawk/MainForm.cs#L597-L600
Not sure which we should go with.

I'm also not sure if the autosave call belongs in `CloseGame`. I believe that runs every time a rom is reloaded or unloaded, including when EmuHawk is closed. Autoload only happens on startup.

**Comment by YoshiRulz** [comment]
Bump?

**Comment by peteyus** [comment]
> 

Saw this, more or less agreed with it... and promptly lost it all in the shuffle of summer craziness with kids. I'll get back to this in the next week or two and apply the changes requested.

**Comment by peteyus** [comment]
> I'm also not sure if the autosave call belongs in CloseGame. I believe that runs every time a rom is reloaded or unloaded, including when EmuHawk is closed. Autoload only happens on startup.

My thinking is that for autosave, it should happen any time the ROM changes. I'm not sure how it worked in FCEUX, although for my use case only doing it on shutdown works. Open to whichever here, calling it on `CloseGame` felt the safest (save early and often) but we could definitely make it happen on shutdown instead to reduce the number of times this happens.

**Comment by peteyus** [comment]
> > I'm also not sure if the autosave call belongs in CloseGame. I believe that runs every time a rom is reloaded or unloaded, including when EmuHawk is closed. Autoload only happens on startup.
> 
> My thinking is that for autosave, it should happen any time the ROM changes. I'm not sure how it worked in FCEUX, although for my use case only doing it on shutdown works. Open to whichever here, calling it on `CloseGame` felt the safest (save early and often) but we could definitely make it happen on shutdown instead to reduce the number of times this happens.

I'm going to do it on CloseGame, it looks like the autoload code is executed during LoadRomInternal as well, so it runs any time the ROM is loaded (not just if it's passed as a command line argument). I think Autosave should have the same logic.

**Review by YoshiRulz — APPROVED** [review]
re: call location, agreed.

LGTM. Will merge tomorrow if no objections.

**Pull request merged**
