### PR TITLE
Simplified identification of PlayStation EXE for RA hash.

### PR DESCRIPTION
**Pull request by prenoeg**
I found another instance of the BOOT line in SYSTEM.CNF containing unexpected characters.  This is similar to the issue with Chrono Cross mentioned in #4085, but this time it's an extra space character with the game Grandia:
```
"BOOT  = cdrom:" vs
"BOOT\t= cdrom:" vs
"BOOT = cdrom:"
```

Normalizing the string again is an option, but I think something different would be better.  According to the following documentation:

https://psx-spx.consoledev.net/cdromfileformats/#cdrom-file-playstation-exe-and-systemcnf

the PlayStation executable path will have the following format:

`"drive:\path\name.ext;version"`

I think we can just pull the executable path from this part of the string by using ':' and ';' as indexes without trying to match "BOOT =" since that part of the string could contain unexpected whitespace characters.  If this is an oversimplification that won't work (in the long run) please let me know, but these changes have been working fine with Grandia, Chrono Cross and the other games I've been testing like Tekken 3 and Wild Arms.

### CODE REVIEW

**Comment by CasualPokePlayer** [comment]
`Akagawa Jirou - Majo-tachi no Nemuri - Fukkatsusai (Japan)` appears to not work under this change, although it doesn't seem to work before regardless. It appears to have this as the BOOT line
`BOOT=cdrom:\SLPS_018.63`

A double odd case here which would break under the old code: no spaces, and the path does not end with `;`, just a newline. The lack of a `;` would break even this newer code.

(Could perhaps be more games like this, this is just the first one I found that had this).

**Comment by YoshiRulz** [comment]
`.SubstringBefore('\n').SubstringAfter('=').Trim().SubstringBefore(';')`?

**Comment by CasualPokePlayer** [comment]
Several other games have the missing ;
```
Arcade's Greatest Hits - The Atari Collection 2 (Europe)
Arcade's Greatest Hits - The Atari Collection 2 (USA)
Astronoka (Japan) (Demo Movie)
Blackjack vs. Matsuda Jun (Japan)
Bust A Move (Japan) (Disc 2) (Premium CD-ROM) (Genteiban)
Chris Kamara's Street Soccer (Europe)
Command & Conquer Complete (Japan) (Disc 1) (GDI)
Command & Conquer Complete (Japan) (Disc 2) (NOD)
Cool Boarders 2 - Killing Session (Japan) (Demo)
Cool Boarders 2 - Killing Session (Japan, Asia)
Cool Boarders 4 (Japan) (Demo)
Crime Crackers 2 (Japan)
D (France) (Disc 1)
D (France) (Disc 2)
D (France) (Disc 3)
D (Germany) (Disc 1)
D (Germany) (Disc 2)
D (Germany) (Disc 3)
D (USA) (Disc 1)
D (USA) (Disc 2)
D (USA) (Disc 3)
Dengeki PlayStation D - Konami Fanbook (Japan)
Dengeki PlayStation D11 (Japan)
Dengeki PlayStation D13 (Japan)
Dengeki PlayStation D14 (Japan)
Dengeki PlayStation D15 (Japan)
Dengeki PlayStation D18 (Japan)
Dengeki PlayStation D19 (Japan)
Dengeki PlayStation D20 (Japan)
Dengeki PlayStation D21 (Japan)
Dengeki PlayStation D22 (Japan)
Dengeki PlayStation D23 (Japan)
Dengeki PlayStation D24 (Japan)
Dengeki PlayStation D25 (Japan)
Dengeki PlayStation D26 (Japan)
Dengeki PlayStation D27 (Japan)
Dengeki PlayStation D28 (Japan)
Dengeki PlayStation D29 (Japan)
Dengeki PlayStation D30 (Japan)
Dengeki PlayStation D31 (Japan)
Dengeki PlayStation D7 (Japan)
Dengeki PlayStation D7 (Japan)
```

**Comment by CasualPokePlayer** [comment]
Pushed my own fixes here: 09d72bf34fd7cb5f64e24c6bf1f11a30276300a2

**Pull request closed without merging**
