### PR TITLE
Make nix buildable from flake (sandbox enabled)

### PR DESCRIPTION
**Pull request by OmnipotentEntity**
Updated the nix files so that they build in a sandboxed environment, such as a nix flake.  An example of such a flake (that you may use to test this) is as follows:

```
{
  inputs = {
    flakeUtils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:nixos/nixpkgs/release-22.05";
    bizhawk.url = "github:OmnipotentEntity/BizHawk/master"; 
    bizhawk.flake = false;
  };
  outputs = { self, ... } @ inputs:
    inputs.flakeUtils.lib.eachSystem [ "x86_64-linux" ] (system:
      let
        pkgs = import inputs.nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        bizhawk = import inputs.bizhawk {
          forNixOS = true;
          pkgs = pkgs;
          mono = pkgs.mono;
          lua = pkgs.lua5_4;
        };

      in rec {
        devShells = {
          # The activation script can be used as dev-shell
          default = pkgs.mkShell {
            buildInputs = with pkgs; [
              bizhawk.emuhawk
              bizhawk.discohawk
              gradle
              jdk11
              gtk2-x11
            ];
          };
        };

        devShell = devShells.default;
      }
    );
}
```

Tested as functional under NixOS.  In order to do this I had to:

1. Add a few packages to the main Nix file (such as speexdsp)
2. Change how nuget files were referenced (`name` was depreciated)
3. Update a handful of packages that had become stale (specifically OpenTK)
4. Remove references to nixpkgs's lib by simply porting the functions over into the file.

[//]: # "Apart from the mandatory license signature, these tasks are optional, but doing them could save reviewers some time and get the PR merged sooner."
Check if completed:
- [ ] I have run any relevant test suites
- [x] I, the committer, have read the [licensing terms for contributors](https://github.com/TASEmulators/BizHawk/blob/master/contributing.md#copyrights-and-licensing) (last updated 2022-07-15) and am compliant

### CODE REVIEW

**Comment by OmnipotentEntity** [comment]
Updated flake.nix because lol lol lol I'm a dumbass and I left a reference to my local filesystem in the flake.  It should now pull from my fork on github and be accessible to anyone.

**Comment by OmnipotentEntity** [comment]
Converting to a draft due to an issue with a lua dependency not being fulfilled, will attempt to fix later on in the week.

**Comment by OmnipotentEntity** [comment]
Fixes the problem with lua not being included on build.  Also fixes the problem with the pkg versions being overridden by the default package `inherit (pkgs)`, moved those to a normal `inherit` statement to prevent this surprising behavior.

**Comment by YoshiRulz** [comment]
I rewrote most of the Nix expression. I didn't add a flake yet, but it seems you didn't end up making any flake-specific changes? If anything comes up you can re-use this PR.

**Pull request closed without merging**
