### PR TITLE
Cleanup before/after frame logic in MovieSession

### LINKED ISSUE #2292: TAStudio records extra frames at the end during playback
In BizHawk 2.4.2 and the latest dev build, there's a very odd difference between TAStudio's behavior and tradional movie recording.

If you create a new movie in TAStudio, and then export to bk2, it will be a 0 frame movie exported.

If you then advance one frame, and export to bk2, it will be a two frame movie. This shouldn't happen; it should be a one frame movie. For some reason, TAStudio will create two new frames.

(I do not think this occurs in Recording Mode for TAStudio, though I need to test that again, but this should not occur at all.)

----

This behavior is not intended, because it was a regression introduced in 2.2.2. There is a similar behavior, where TAStudio always has a blank line at the end. For instance, if you click a button on the last line of TAStudio, it will add a single line afterwards. However, this is a distinct behavior, and only adds *one* frame, not two.

Also comparable, as mentioned above, TAStudio always starts with a single line, which actually translates into a 0-frame movie. And this seems like a sensible behavior to me, since nothing has occurred in the movie.

Ideally, TAStudio would always shows one more input line than the size of the movie's input log. This bug breaks that, and limits the ability to control TAStudio's playback precisely. For instance, this bug is a blocker for TAStudio being able to (conveniently) calculate the cycle count in Game Boy movies. *Edit* (2024-06-24): Yes, you can seek to the desired "last" frame and truncate, and that could save cycle count if saving cycle count in TAStudio worked, but ideally that wouldn't even be necessary.

----

I am going to try and address this in the [moviesession-cleanup](https://github.com/TASVideos/BizHawk/compare/moviesession-cleanup) branch.

----

This bug was introduced between 2.2.1 and 2.2.2. Specifically, it was introduced in e99ea11cf7e18309a05d1c58d38ca13dea808120.

### PR DESCRIPTION
**Pull request by Morilli**
-closes #2292.

This does change some behavior, but hopefully the new structure is more logical and more correct. Calling `HandleFrameAfter` from `HandleFrameBefore` definitely didn't feel proper.

This is in preparation for #3989, as this changed logic should be much clearer in what specific changes TAStudio wants: If the current playback is at the end of the movie,
1. the `HandlePlaybackEnd` function should not be called and instead the movie should just stay in the mode it was previously in
2. on frame advance, input should still be recorded, even in playback mode.

The 2. point is the biggest question mark to me still. There is this line `MovieController.SetFromSticky(StickySource);` which can currently only be hit on the very first frame or when enabling recording mode, advancing to the end of the tas movie, disabling recording mode and then advancing a single frame without entering input in the input roll.
If I knew how to get sticky/autohold input I would test it, although I'm assuming the current logic is incorrect if anything.

Could maybe also help with #2622, although that will require additional consideration.

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Which of the things described in #2292 does it fix?

**Comment by Morilli** [comment]
> Which of the things described in #2292 does it fix?

The part where TAStudio always keeps an extra frame at the end in playback mode. The behavior is now effectively the same as record mode. When pressing frame advance after creating a new tasproj, the movie will have a 1 frame length.

**Comment by vadosnaprimer** [comment]
Alright yep, I think this fix makes it possible to properly set movie duration on its last frame in tastudio. When we've emulated the last frame of the tasproj, we're in the same state as if we've just recorded a regular movie. Obviously drawing on last frame in the InpuRoll adds one more row which is correct, but having playback cursor on that frame should not have added yet another frame to the movie, because the fact of emulating it does not require any new frames.

**Comment by vadosnaprimer** [comment]
> on frame advance, input should still be recorded, even in playback mode.

I disagree with this if it's not optional.

**Comment by Morilli** [comment]
> > on frame advance, input should still be recorded, even in playback mode.
> 
> I disagree with this if it's not optional.

This is just how TAStudio has worked the last couple years. The alternative would be to respect the "on movie end" setting completely, but then you'd get a switch to record mode at the end, which may or may not be what people expect when using TAStudio.

**Pull request merged**
